### ISSUE TITLE
scrollToAnchor() doesn't scroll to offset 

### ISSUE THREAD

**Issue by urbgimtam** [helltraitor/nuxt-anchorscroll#1]
Hello and thank you for your module! I'm facing an issue I cannot fix and seems to be a bug. But maybe I'm just not understanding correctly, so sorry if its that.

I have a top menu, and the menu items should scroll to anchors in the page.
They are defined like this:
```
<ul>
<li>
  <NuxtLink :to="/" @click="scrollToTop()>
    LOGO
  </NuxtLink>
</li>

<li v-for="menuItem in listOfMenuItems" :key="menuItem.id">
   <NuxtLink  :to="{path: '/', hash: `#${menuItem.id}`}"  @click="scrollToAnchor(menuItem.id)">
       {{ menuItem.title }}
   </NuxtLink>
</li>
</ul>
```

I've also defined scrollToAnchor: 
```
const { scrollToAnchor, scrollToTop } = useAnchorScroll({
  scrollOptions: {
    behavior: 'smooth',
    offsetTop: -400,
  },
})
```

Clicking on an element using scrollToAnchor(), it scrolls to the element, but with offsetTop 0. 
Changing its value in scrollOptions also does not affect the outcome. It always scrolls to offsetTop: 0.

However, I've also noticed that it does affect the scroll of scrollToTop(). 

At the moment, I'm kind of lost, but was expecting for scrollToAnchor() to respect the offsetToTop.

Thank you and sorry to bother.

**Comment by urbgimtam** [comment]
I've forgot to let you know that, in the meantime, I've mitigated the issue by adding styling with `display: absolute; top: -40px` on the anchor target.

**Comment by helltraitor** [comment]
> They are defined like this:

This code has syntax errors, so be caution next time:

```html
<NuxtLink :to="/" @click="scrollToTop()>
    LOGO
</NuxtLink>
```

> Clicking on an element using scrollToAnchor(), it scrolls to the element, but with offsetTop 0.

Does it respects the `behavior` value? As for now, I'm not sure which layout you're using.
So the first question: **Does anchors working without `nuxt-anchorscroll` module?**

If so, then we have a conflict between module and browser. In this case we must mangle hash.
This was described in [playground](https://stackblitz.com/github/helltraitor/nuxt-anchorscroll?file=playground%2Fapp.vue) (standard layout).

---

When I've tried to put your code in playground site, nothing happen. Seems like you forgot to put `id` in link tag:

```html
<!-- Put id in v-for, as written below -->
<li v-for="menuItem in listOfMenuItems" :key="menuItem.id" :id="menuItem.id">
   <!-- Or put it in NuxtLink, but don't use same id twice (just choose where to put it) -->
  <NuxtLink :to="{path: '/test', hash: `#${menuItem.id}`}" @click="scrollToAnchor(menuItem.id)" :id="menuItem.id">
    {{ menuItem.title }}
  </NuxtLink>
</li>
```

Correct example:
```
<li v-for="menuItem in listOfMenuItems" :key="menuItem.id" :id="menuItem.id">
  <NuxtLink :to="{path: '/test', hash: `#${menuItem.id}`}" @click="scrollToAnchor(menuItem.id)">
    {{ menuItem.title }}
  </NuxtLink>
</li>
```

---

Repeating again:

1. Add `id` to your elements
2. Determine, which layout you're using

So, put some link to this page with `test` hash, put some element with same id and click. On preferred layout **happens nothing**, on standard - **scroll to element** (browser implementation, that conflicts with module). In playground is described how to handle this.

---

Text me, when you put id in elements and know your layout type (additionally, you can try to fix it by yourself by following the examples and explanations in README and playground). Good luck!

**Comment by helltraitor** [comment]
@urbgimtam 
If this is no longer an issue - I will close this topic on 15 of October
